name: Push to heroku

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Release API
      uses: akhileshns/heroku-deploy@v3.0.4
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "bbycrm-api"
        heroku_email: ${{secrets.HEROKU_API_KEY}}
      env:
        HD_APP_BASE: "back-end"
        HD_MONGODB_CONNECTION: ${{secrets.MONGODB_CONNECTION_STRING}}
    - name: Release Web Client
      uses: akhileshns/heroku-deploy@v3.0.4
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "bbycrm"
        heroku_email: ${{secrets.HEROKU_API_KEY}}
      env:
        HD_APP_BASE: "front-end"
        HD_REACT_APP_API_URL: "https://bbycrm-api.herokuapp.com"
  run-tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install newman
      uses: actions/setup-node@v1
      with:
          node-version: '14'
      run: npm install -g newman
    - name: Run Postman Tests
      run: newman run PostmanTesting/BbyCrmTestSuite.postman_collection.json -e PostmanTesting/BbyCrmTestEnv.postman_environment.json